const state={bank:[],test:null};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function qtime(){return 20*60}
function score(qs){let units=0,c=0,w=0,u=0; for(const q of qs){const a=q.userAnswer;if(!a){u++;continue} if(a===q.canonical_answer){c++;units+=4}else{w++;units-=1}} return {c,w,u,score:units/4,accuracy:c/(c+w||1)} }
function save(){localStorage.setItem('sbi_cbt_active',JSON.stringify(state.test))}
function startTest(mode='full'){const sec=[['English',30],['Quant',35],['Reasoning',35]]; const qs=[]; for(const [s,n] of sec){let pool=state.bank.filter(q=>q.section===s); pool=[...pool].sort(()=>Math.random()-.5); qs.push(...pool.slice(0,n).map(q=>({...q,userAnswer:null,marked:false,spent:0})));} state.test={id:'PRACTICE-'+Date.now(),start:Date.now(),sectionIndex:0,sectionStart:Date.now(),sectionEnd:Date.now()+qtime()*1000,qs,idx:0}; save(); render(); }
function current(){return state.test.qs[state.test.idx]}
function next(){if(state.test.idx<state.test.qs.length-1)state.test.idx++;render()}
function prev(){if(state.test.idx>0)state.test.idx--;render()}
function select(i){state.test.idx=i;render()}
function toggleMark(){current().marked=!current().marked;save();render()}
function choose(a){current().userAnswer=a;save();render()}
function submit(){clearInterval(window.tmr); const r=score(state.test.qs); localStorage.removeItem('sbi_cbt_active'); localStorage.setItem('sbi_result_'+state.test.id,JSON.stringify({test:state.test,result:r,at:new Date().toISOString()})); showResult(r) }
function tick(){const t=state.test; const left=Math.max(0,t.sectionEnd-Date.now()); const m=Math.floor(left/60000),s=Math.floor(left/1000)%60; const el=$('#timer'); if(el)el.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`; if(left<=0){ if(t.sectionIndex<2){t.sectionIndex++;t.sectionStart=Date.now();t.sectionEnd=Date.now()+qtime()*1000;save();} else submit(); }}
function render(){if(!state.test)return renderHome(); const q=current(),t=state.test,sec=['English','Quant','Reasoning'][Math.min(t.sectionIndex,2)]; const opts=Object.entries(q.options); let html=`<div class="top"><div><b>SBI Clerk Prelims CBT</b><div class="muted" style="color:#dce8f6">${sec} · Q ${t.idx+1}/${t.qs.length}</div></div><div class="stat" id="timer">20:00</div></div><div class="main"><div class="grid"><div class="card"><div class="muted">${esc(q.topic||'Unclassified')}</div><h3>${esc(q.question)}</h3>${opts.map(([k,v])=>`<label class="option"><input type="radio" name="opt" ${q.userAnswer===k?'checked':''} onchange="choose('${k}')"> <b>${k}.</b> ${esc(v)}</label>`).join('')}<div class="bar"><button class="btn" onclick="prev()">Previous</button><button class="btn ${q.marked?'danger':'primary'}" onclick="toggleMark()">${q.marked?'Unmark':'Mark for Review'}</button><button class="btn primary" onclick="next()">Save & Next</button><button class="btn danger" onclick="submit()">Submit Test</button></div></div><div class="card"><h3>Question Palette</h3><div class="palette">${t.qs.map((x,i)=>`<button class="qbtn ${i===t.idx?'current ':''}${x.userAnswer?'answered ':''}${x.marked?'marked':''}" onclick="select(${i})">${i+1}</button>`).join('')}</div><p class="muted">Answered: ${t.qs.filter(x=>x.userAnswer).length} · Unanswered: ${t.qs.filter(x=>!x.userAnswer).length} · Marked: ${t.qs.filter(x=>x.marked).length}</p></div></div></div>`; $('#app').innerHTML=html; tick(); clearInterval(window.tmr);window.tmr=setInterval(tick,250); }
function renderHome(){ $('#app').innerHTML=`<div class="top"><b>SBI Clerk Prelims CBT</b><span>GitHub Pages ready</span></div><div class="main"><div class="card"><h1>20-Minute SBI Clerk Practice</h1><p>100 questions · English 30 · Quant 35 · Reasoning 35 · +1 / -0.25 / 0</p><p class="muted">The live CBT uses only verified records from the preprocessed question bank.</p><button class="btn primary" onclick="startTest()">Start Full Mock</button></div></div>` }
async function boot(){const r=await fetch('data/questions.json'); state.bank=await r.json(); renderHome();}
boot();